### ISSUE TITLE
腾讯音源有些歌听不了呢

### ISSUE THREAD

**Issue by rong-zhi-yi** [ZxwyWebSite/lx-source#16]

**Comment by ZxwyWebSite** [comment]
0. 默认试听模式，游客登录无法听的歌自然也无法获取

1. 如果登录账号，并且开启刷新登录，这是一个Bug，尝试将 `[Custom].Tx_Refresh_Interval` 清零后重启程序，若刷新失败请重新获取账号数据

3. 其它情况，请提供 MusicId 或 Debug日志 以供复现问题
