### ISSUE TITLE
ztool 需要更新下了吧，有些方法都找不到了

### ISSUE THREAD

**Issue by huangweiboy2** [ZxwyWebSite/lx-source#17]
![image](https://github.com/ZxwyWebSite/lx-source/assets/56343299/fa39e786-2fb3-4afb-8aff-7f6d59fcc02f)

**Comment by ZxwyWebSite** [comment]
(测试版，部分功能暂未完善)
<https://r2eu.zxwy.link/gh/lx-source/static/ztool-20240206-1238.zip>

**Comment by jtaosj** [comment]
> (测试版，部分功能暂未完善) https://r2eu.zxwy.link/gh/lx-source/static/ztool-20240206-1238.zip

下载不了

**Comment by ZxwyWebSite** [comment]
可在 `.github/workflows/action.yml #Fetch Modules` 找到最新远程库地址
