### ISSUE TITLE
简易使用教程

### ISSUE THREAD

**Issue by ZxwyWebSite** [ZxwyWebSite/lx-source#23]
~~(文档太麻烦不做了，写在这里自己看吧)~~

### 0. 注意事项
1. 配置文件不支持热重载并且以后也不打算支持，所以每次修改**重启程序**生效
2. 有时候日志信息非常有用，提问前将调试模式打开并尝试复现问题，提问时附上请求日志有助于更快的定位问题
3. **不要过度依赖内置源，仅供测试不保证可用性，想稳定还是要自备账号**

### 1. 下载程序
+ 进入 [Release](https://github.com/ZxwyWebSite/lx-source/releases) 页面，下载最新版本，中国大陆用户可尝试使用CDN链接
+ 将程序解压到空白目录，运行程序
+ 复制连接码备用（`Ctrl+C` 安全关闭程序）
- **法1: 自行修改脚本 ↓**
- 在 `data/public` 找到 `lx-custom-source.js`
- 右键记事本打开，将连接码填入 apipass 后的单引号内
- 如无需调试可将 devmode 改为 false
- 保存退出，将源脚本导入洛雪音乐
+ **法2: 自动填写脚本 ↓**
+ 配置文件转到 [Script] 将 Auto 改为 2
+ 重启程序，访问 http://127.0.0.1:1011/lx-custom-source.js?raw 下载脚本
+ 导入洛雪音乐即可使用
+ 公开环境建议将 Auto 改回 0 或 1 以防连接码泄露
- **公开访问（服务器部署）**
- 如有Nginx反代不用改监听地址，将 [Main].NgProxy 改为 true 启用反代兼容
- 否则将 [Main].Listen 改为 `{服务器ip}:{端口号}` 或直接 `:{端口号}`（不带大括号）
- 如需使用本地缓存还需将 [Cache].Local_Bind 改为外部访问地址或开启自适应(beta)
- 然后将脚本中的 apiaddr 改为实际访问地址，保证路径最后为 `/`

### 2. 配置账号
+ 打开配置文件并转到 [Custom] 区域
+ 参考注释填写账号参数
+ 将对应平台的 _Enable 项改为 true（解锁全部支持音质）
+ 建议启用刷新登录功能，以防Token过期
+ 保存文件，重启程序，重新初始化脚本或重启洛雪音乐
- **Wy源:**
- 打开网页版登录账号，F12→应用程序→Cookie 复制 MUSIC_U 值备用
- 将 Wy_Mode 改为 163api，Wy_Api_Address 填写 `MUSIC_U={刚才复制的值}`（不带大括号）
+ **Kg源:**
+ (需要一定技术基础，新手不建议尝试)
+ 将旧手机root后安装官方客户端登录账号抓包，看Header里的token和userid参数
- **Tx源:**
- 网页端登录账号，F12→应用程序→Cookie 备用
- 将 _uin 结尾的值填入 Tx_Uuin，_key 结尾的值填入 Tx_Ukey

### 3. 配置详解
+ [Source].Enable_Xx 和 [Custom].Xx_Enable 是什么关系：
   - Enable_Xx 为总开关，可在此处彻底禁用某一音乐源
   - Xx_Enable 为分开关，标记是否启用自定义账号功能，解锁全部音质（关闭状态仅可获取128k试听音质）

### 4. 访问控制
+ **Key验证** (简单验证请求连接码)
   - 连接码不宜过长也不宜过短，过长影响性能，过短影响安全
+ **速率限制** (一个简单的限制请求频率的中间件，暂未完善)
   - 原理：记录访问者ip和一定时间段内请求次数，若超限则阻止继续解析，超出容忍限度则延长封禁时间

未完待续...

**Comment by ZxwyWebSite** [comment]
> 酷我的呢，大佬
@zhangyouxin123
Kw源无需额外配置，可直接使用

**Comment by zhangyouxin123** [comment]
还有一个要请教你，为什么QQ音乐下了十几首就其他的显示下载失败或者是下载的是语音提示歌曲未授权什么之类的
![QQ截图20240329224012](https://github.com/ZxwyWebSite/lx-source/assets/35016819/d1df04ee-fe96-4500-8773-b2c4fccabb16)这是我的配置速率的图

**Comment by ZxwyWebSite** [comment]
@zhangyouxin123

语音提示与速率限制无关，请求过快不会返回错误语音：
```json
{
    "code": 5,
    "msg": "请求过快，请稍后重试",
    "data": null
}
```
另外，速率限制不是你那么配置的，提高一段时间内最大解析量应该修改单IP速率限制，与容忍限度无关。没有共享需求基本用不到可以关掉

下载失败一般就是无法获取音乐链接（账号无权限、游客无法试听等）
可通过开启 "[Source].ForceFallback" 提升成功概率（自动依次尝试 '指定音质'→'128k'→'试听'）
但可能会出现音质不对（指定320k返回128k）或只有试听（音频不全）等问题，请酌情考虑是否开启

（如需定位详细问题请提供Debug日志或具体音乐信息以便复现）
附图：
![2024-03-29_01](https://github.com/ZxwyWebSite/lx-source/assets/112370739/971dcff4-1e44-486e-8140-566f536d6496)

**Comment by zhangyouxin123** [comment]
下载失败一般就是无法获取音乐链接（账号无权限、游客无法试听等）这种可以设置直接返回错误吗？下载出来的连空的都有

**Comment by imAndyrrr** [comment]
![W$D{S_X@KKRP0}BUAL7O0VH](https://github.com/ZxwyWebSite/lx-source/assets/167629228/0de41846-9e0a-4510-8d91-c96141b2647f)

你好，请问全都401（验证失败）是怎么回事

**Comment by ZxwyWebSite** [comment]
@imAndyrrr 
请求头没有携带验证密钥，请检查源脚本是否填写apipass
可参考上方文档 **1. 下载程序** 中的 **法1**或**法2** 进行修改
或直接在配置文件中关闭Key验证 (首页readme有视频教程)

**Comment by 1124714647** [comment]
![微信截图_20240505011708](https://github.com/ZxwyWebSite/lx-source/assets/44636698/4a24eecf-172f-4e3c-a748-dc167f825270)
请问一下503获取不了的怎么改成不替换提示音，因为歌单下载下来503的也一起下载了 结果打开就全是提示音 怎么设置成获取失败

**Comment by ZxwyWebSite** [comment]
@1124714647
目前无解，逻辑写死在MusicHandler里了，只能等待下个版本更新相关配置开关
最开始支持的平台少，为了防止自动换源机制瞎查(同样关不掉)，只要没有解析结果就返回默认提示音频
而且我不经常下载，更习惯于手动换源，平常都直接用服务端缓存听，确实没考虑到这一方面

**Comment by 1124714647** [comment]
@ZxwyWebSite 就等你下个版本了 部署在服务器上面哪个环境比较适合

**Comment by 1124714647** [comment]
自动配置填写 Auto = 2  我的监听地址已经改为Listen = 192.168.0.188:1011   
然后http://192.168.0.188:1011/lx-custom-source.js?raw 获取的脚本里面的地址还是127.0.0.1 这个不能自动填写我conf.ini配置里面的监听地址吗

**Comment by 1124714647** [comment]
![PixPin_2024-06-21_16-48-44](https://github.com/ZxwyWebSite/lx-source/assets/44636698/037f9be4-316a-4560-926d-c9be5cd1752a)
[LX-SOURCE] [Error] 2024-06-21 16:46:01 [Wy] HttpReq: "Syntax error no sources available: decoder.SyntaxError{Pos:1136, Src:\"\", Code:0x0, Msg:\"\"}"
报错的这些歌曲实际是有有音源可听的

**Comment by ZxwyWebSite** [comment]
@1124714647 

1
目前自动填写配置的监听地址使用的是 [Cache].Local_Bind 的值

2
已测试前两个获取失败的歌曲，大概是你本地网络问题导致没有获取到数据
**wy/1462081840/128k:**
```text
[LX-SOURCE] [Debug] 2024-06-29 00:54:53 [MusicHandler] s:'wy', m:'link', id:'1462081840', q:'128k'
[LX-SOURCE] [Debug] 2024-06-29 00:54:53 [MusicHandler] MemoGet: link/wy/1462081840/128k
[LX-SOURCE] [Debug] 2024-06-29 00:54:53 [MusicHandler] FileGet: wy/1462081840/128k.mp3
[LX-SOURCE] [Debug] 2024-06-29 00:54:53 [Wy] Resp: &{Data:[{ID:1462081840 URL:http://m8.music.126.net/20240629011955/2ceab734417554f5eddbb214dc3eed82/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3201473730/d73f/7a5d/78cc/afd9484d76d531edede6e8ea4d84adfa.mp3 Br:128002 Size:2946093 Md5:afd9484d76d531edede6e8ea4d84adfa Code:200 Expi:1200 Type:mp3 Gain:-10.3008 Peak:1 Fee:8 Uf:<nil> Payed:1 Flag:2064388 CanExtend:false FreeTrialInfo:<nil> Level:standard EncodeType:mp3 FreeTrialPrivilege:{ResConsumable:false UserConsumable:false ListenType:0 CannotListenReason:0 PlayReason:<nil>} FreeTimeTrialPrivilege:{ResConsumable:false UserConsumable:false Type:0 RemainTime:0} URLSource:0 RightSource:0 PodcastCtrp:<nil> EffectTypes:<nil> Time:184060}] Code:200}
[LX-SOURCE] [Debug] 2024-06-29 00:54:54 [MusicHandler] FileSet: http://m8.music.126.net/20240629011955/2ceab734417554f5eddbb214dc3eed82/ymusic/obj/w5zDlMODwrDDiGjCn8Ky/3201473730/d73f/7a5d/78cc/afd9484d76d531edede6e8ea4d84adfa.mp3
```
**kw/40492248/320k:**
```text
[LX-SOURCE] [Debug] 2024-06-29 01:00:21 [MusicHandler] s:'kw', m:'link', id:'40492248', q:'320k'
[LX-SOURCE] [Debug] 2024-06-29 01:00:21 [MusicHandler] MemoGet: link/kw/40492248/320k
[LX-SOURCE] [Debug] 2024-06-29 01:00:21 [MusicHandler] FileGet: kw/40492248/320k.mp3
[LX-SOURCE] [Debug] 2024-06-29 01:00:21 [Kw] Resp: &{Code:200 Locationid:1 Data:{Bitrate:320 User: Sig:6135285376324634848 Type:0 Format:mp3 P2PAudiosourceid:15413435030106trackmediaM800003ZCfPu1puskfmp3 Rid:40492248 URL:http://lw.sycdn.kuwo.cn/04a27ce112338e83dadace849a2910fd/667eec25/resource/30106/trackmedia/M800003ZCfPu1puskf.mp3} Msg:ok}
[LX-SOURCE] [Debug] 2024-06-29 01:00:21 [MusicHandler] FileSet: http://lw.sycdn.kuwo.cn/04a27ce112338e83dadace849a2910fd/667eec25/resource/30106/trackmedia/M800003ZCfPu1puskf.mp3
```
