### ISSUE TITLE
exe文件双击运行没反应

### ISSUE THREAD

**Issue by goodpangpang** [ZxwyWebSite/lx-source#24]
releases下载的exe文件运行没有反应，请问大佬这是啥原因呢，谢谢

**Comment by ZxwyWebSite** [comment]
程序所在目录按住Shift+鼠标右键在此处打开命令窗口，输入 `lx-source-windows-amd64v2.exe` 回车以命令行方式运行
如果是PowerShell输入 `./lx-source-windows-amd64v2.exe`，复制控制台输出或截图上传
另外从Go1.21开始不再支持win7及以下系统，如果是的话可以先去尝试另一个同类型的Python版项目
[lxmusics/lx-music-api-server-python](https://github.com/lxmusics/lx-music-api-server-python)

(开学后只有每周六会上线回复，请耐心等待)
