### ISSUE TITLE
这个文件找不到报错是什么情况？

### ISSUE THREAD

**Issue by fykcy** [ZxwyWebSite/lx-source#25]
go: github.com/ZxwyWebSite/ztool@v0.0.1 (replaced by ./pkg/ztool): reading pkg/ztool/go.mod: open /Users/Desktop/WWW/GoProject/lx-source/pkg/ztool/go.mod: no such file or directory

**Comment by ZxwyWebSite** [comment]
部分依赖项处于测试阶段，暂未正式发布
