### ISSUE TITLE
开了网易会员的话，怎么配置给洛雪使用？要求有点特殊哈

### ISSUE THREAD

**Issue by markxsq** [ZxwyWebSite/lx-source#26]
因为孩子播放器里只安装了洛雪。
目前按大佬的这个发布部署，只有 小枸和小秋能播放，网易的源无法播放

**Comment by ZxwyWebSite** [comment]
Wy源内置接口已失效，支持配置自定义账号，步骤如下：

0. 准备电脑浏览器环境
1. 官方网页版登录会员账号
2. F12打开开发者工具→应用程序→Cookie，复制MUSIC_U值备用
3. 配置文件 data/conf.ini 往下翻，修改以下内容
   ```ini
   [Custom]
   Wy_Enable = true
   Wy_Mode = 163api
   Wy_Api_Type = native
   Wy_Api_Cookie = MUSIC_U=粘贴刚才复制的值
   Wy_Refresh_Enable = true
   ```
4. 重启服务端，清除洛雪歌曲URL缓存，如无报错即可正常使用

附图：
![2024-03-22_01](https://github.com/ZxwyWebSite/lx-source/assets/112370739/f5cc5758-7ece-4c23-acf6-e34fa7a6f106)

(开学后只有每周六上线回复，非此时间段请耐心等待)
