### ISSUE TITLE
开了网易云会员，但是vip的歌只能放20秒

### ISSUE THREAD

**Issue by Demon0H** [ZxwyWebSite/lx-source#27]
我的网易云音乐账户开通了vip，但是网易云vip的歌都只能播放20秒，部分不能播放

**Comment by ZxwyWebSite** [comment]
see: https://github.com/ZxwyWebSite/lx-source/issues/26#issuecomment-2015245029

正常使用只需填写 MUSIC_U 部分即可
如果粘贴的是完整Cookie请在数据前后加上转义符 `
(配置文件会自动格式化，没加转义符会导致只识别第一个数据，; 后面的被当作注释处理掉，然后刷新成游客账号)
```ini
[Custom]
Wy_Enable = true
Wy_Mode = 163api
Wy_Api_Type = native
Wy_Api_Cookie = `MUSIC_R_T=1626952293038; MUSIC_U=xxxxxx`
Wy_Refresh_Enable = true
```
请检查配置文件填写格式是否正确，以及Cookie是否只剩下第一条数据
