### ISSUE TITLE
小秋音乐下载失败

### ISSUE THREAD

**Issue by lancer-wang** [ZxwyWebSite/lx-source#31]
用的 5-25日的
[lx-source-linux-amd64v2.zip](https://github.com/ZxwyWebSite/lx-source/releases/download/v1.0.3.0525/lx-source-linux-amd64v2.zip)

![image](https://github.com/ZxwyWebSite/lx-source/assets/69783837/a98c8842-0da8-4a05-9c13-1b73dd071221)

![image](https://github.com/ZxwyWebSite/lx-source/assets/69783837/d345f4a3-9595-4393-9fe3-d943ad164b01)

![image](https://github.com/ZxwyWebSite/lx-source/assets/69783837/82917fdc-4dfb-4ea3-ad47-8480147b11f3)

**Comment by lancer-wang** [comment]
![image](https://github.com/ZxwyWebSite/lx-source/assets/69783837/eb09ba0f-4d23-4be3-8625-5aae085db5e2)

连普通音质都下载不了
，不知道为什么

**Comment by lancer-wang** [comment]
奇怪的是，高品音质可以下载
![image](https://github.com/ZxwyWebSite/lx-source/assets/69783837/a6f14cb3-332d-4c43-83c9-88dc8d6f6eb9)

![image](https://github.com/ZxwyWebSite/lx-source/assets/69783837/be5b605a-e74f-4d5d-a47a-f502d584528c)

**Comment by lancer-wang** [comment]
经过我多次测试

我发现，普通和无损点击下载之后，debug 那边什么反应都没有

只有高频音质会有输出内容
是不是普通和无损没能请求到？

**Comment by ZxwyWebSite** [comment]
洛雪音乐有缓存，如果没有请求日志就是使用缓存链接了，到 **设置 > 其他 > 其他缓存管理** 清理一下歌曲URL缓存 即可
还可以通过浏览器访问服务端手动测试 <http://127.0.0.1:51011/link/tx/004KWIe52XhNKl/320k>
音乐ID为歌曲右键详情页链接最后一段 <https://y.qq.com/n/ryqq/songDetail/004KWIe52XhNKl>
另外：伪装IP功能未实装，实际并无作用 😅

**Comment by lancer-wang** [comment]
大概是因为这个，我换个电脑试试

**Comment by lancer-wang** [comment]
![image](https://github.com/ZxwyWebSite/lx-source/assets/69783837/3bc36618-7098-4253-a28f-0492089d7356)

浏览器访问那几个无效的歌曲是返回这个，不知道是为啥

**Comment by ZxwyWebSite** [comment]
服务端还有一层缓存，获取失败会拒绝同ID请求10分钟，如需快速恢复可先关闭程序后删除 `data/memo.bin`
