### ISSUE TITLE
[已解决] 网易 音源 无法连接解析接口

### ISSUE THREAD

**Issue by HittyGubby** [ZxwyWebSite/lx-source#37]
![image](https://github.com/user-attachments/assets/b1658587-a14f-424a-9575-1f4240de7d9c)
网易的API请求返回全部503，显示 无法连接解析接口

logfile.log 日志文件有关内容： 
```
[GIN] 2024/07/24 - 01:48:51 | 503 |      74.536µs |       127.0.0.1 | GET      "/url/wy/29393421/128k"
[LX-SOURCE] [Debug] 2024-07-24 01:48:54 [MusicHandler] s:'wy', m:'url', id:'32719660', q:'128k'
[LX-SOURCE] [Debug] 2024-07-24 01:48:54 [MusicHandler] MemoGet: url/wy/32719660/128k
[LX-SOURCE] [Debug] 2024-07-24 01:48:54 [MusicHandler] FileGet: wy/32719660/128k.mp3
[LX-SOURCE] [Error] 2024-07-24 01:48:54 [Wy] HttpReq: Mismatch type int64 with value string "at index 47: mismatched type with value\n\n\t          \"id\": \"11451\",\r\n      \n\t................^...............\n"
```

**Comment by ZxwyWebSite** [comment]
内置解析接口寄了。配置文件把 [Custom].Wy_Mode 改为 163api，暂时切换至官方接口
如有账号可填写Cookie，部分非会员歌曲最高可获取到320k音质
然后等1.1更新，目前已搜集到2个可用接口

**Comment by HittyGubby** [comment]
使用163api必须填写cookie吗？
我把改成163api之后 输出显示 `[WyInit] 使用163api且Cookie参数为空`

**Comment by ZxwyWebSite** [comment]
不填写Cookie或Cookie过期只能获取128k音质，不想填可以随便填写 `k=v`，绕过初始化检测

**另：**

趁这几天接口没开白名单赶紧下载，替换参数后浏览器访问以下链接，返回的url就是下载地址

`https://csm.sayqz.com/api/?type=apiSongUrlV1&id=${音乐ID}&level=${音质}&cookie=MUSIC_U=aadead`

音质: standard=>标准128k, higher=>较高192k, exhigh=>极高320k, lossless=>无损flac, hires=>Hi-Res, jyeffect=>高清环绕声, sky=>沉浸环绕声, jymaster=>超清母带

MUSIC_U 参数可随意填写，但不可为空，否则会返回错误提示，这就是内置源失效的原因

例如: `https://csm.sayqz.com/api/?type=apiSongUrlV1&id=27510174&level=exhigh&cookie=MUSIC_U=aadead`

=> {"data":[{"id":27510174,"url":"**http://m7.music.126.net/20240724031503/b5a5b0a6e6ebd72e1e676dd9322a5b20/ymusic/599d/df13/ef95/44e10c943d81ebbc39d65a25f49eb6c6.mp3**","br":320000,"size":10900516,"md5":"44e10c943d81ebbc39d65a25f49eb6c6","code":200,"expi":1200,"type":"mp3","gain":-9.2847,"peak":1,"fee":0,"uf":null,"payed":0,"flag":1605888,"canExtend":false,"freeTrialInfo":null,"level":"exhigh","encodeType":"mp3","channelLayout":null,"freeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"listenType":null,"cannotListenReason":null,"playReason":null,"freeLimitTagType":null},"freeTimeTrialPrivilege":{"resConsumable":false,"userConsumable":false,"type":0,"remainTime":0},"urlSource":0,"rightSource":0,"podcastCtrp":null,"effectTypes":null,"time":272000,"message":null,"levelConfuse":null}],"code":200}

**2024-08-01 Update:**

上方演示音乐被换源，事实再次证明缓存的重要性，感兴趣的可顺着音乐ID到[评论区](https://music.163.com/#/song?id=27510174)围观

楼上题主删评了，原本问的大概是 "不填写Cookie就不让启动，是必须填的吗"，并附上报错截图
