### ISSUE TITLE
搜索页面只有tx有结果

### ISSUE THREAD

**Issue by WWz33** [ZxwyWebSite/lx-source#5]
搜索结果只能搜出tx的音源，其他音源列表加载失败

**Comment by ZxwyWebSite** [comment]
0. 是否按要求更新源脚本到最新版
1. 搜索功能与本解析程序无关，由洛雪音乐实现，请检查能否访问各平台搜索Api
2. 列表加载失败是指显示 `啊，加载失败了😭` 吗？本地网络问题，请刷新重试

**Comment by ZxwyWebSite** [comment]
问题过期未回复，关闭此issue。
