### ISSUE TITLE
不知能否有部署到私人vps的教程？自用不公开。

### ISSUE THREAD

**Issue by azx4833** [ZxwyWebSite/lx-source#6]
因为不是很懂IT，不过有个机是自用梯，想着这样就不用每次都本地启动服务端了。万分感谢

**Comment by ZxwyWebSite** [comment]
国内音乐平台接口不支持在国外调用（可能会出现因为异地登录而封号、部分版权受限、mg源无法使用等问题）
目前必须本地部署（我就是在海思盒子上运行的）

如需内网公开访问请进行以下修改 (演示ip替换为实际地址)
配置文件：
`[Main].Listen` 改为 `<本机ip>:1011`
`[Cache].Local_Bind` 改为 `http://<本机ip>:1011/`
```ini
[Main]
Listen = 192.168.10.32:1011
[Cache]
Local_Bind = http://192.168.10.32:1011/
```
源脚本：
`apiaddr` 改为 `http://<本机ip>:1011/`
```js
const apiaddr = 'http://192.168.10.32:1011/'
```
其它：
Windows第一次运行弹防火墙警告时是否允许访问

**Comment by azx4833** [comment]
> 国内音乐平台接口不支持在国外调用（可能会出现因为异地登录而封号、部分版权受限、mg源无法使用等问题） 目前必须本地部署（我就是在海思盒子上运行的）
> 
有道理 ，是我考虑不周了。
